#: import hex kivy.utils.get_color_from_hex


<AddProdutoScreen>:

    FloatLayout:
        md_bg_color: hex('#aaabbb')

        MDTopAppBar:
            title: 'Cadastro de Produto'
            md_bg_color: hex('#D8BFD8')
            specific_text_color: app.theme_cls.primary_color
            elevation: 0
            pos_hint: {'top': 1}
            left_action_items: [["arrow-left", lambda x: root.back()]]

        MDLabel:
            id: retorno
            font_style: 'H5'
            bold: True
            halign: "center"
            color: 139,0,139,1
            pos_hint: {"center_y": 0.83}

        MDScrollView:
            pos_hint: {"center_y": 0.55}

            MDBoxLayout:
                orientation: 'vertical'
                spacing: 5

                MDTextField:
                    id: codigo
                    hint_text: "Codigo (opcional)"
                    pos_hint: {"center_x": 0.5}
                    size_hint_x: .8
                    password: False
                    icon_right: 'tag'
                    input_filter: 'int'
                    icon_right_color: app.theme_cls.primary_color
                    helper_text: "Caso o código não seja informado, ele será gerado automaticamente"
                    helper_text_mode: "on_focus"
                    write_tab: False

                MDTextField:
                    id: barcode
                    hint_text: "Codigo de barras (opcional)"
                    pos_hint: {"center_x": 0.5}
                    size_hint_x: .8
                    password: False
                    icon_right: 'barcode'
                    input_filter: 'int'
                    icon_right_color: app.theme_cls.primary_color
                    helper_text: "Caso o código não seja informado, ele será gerado automaticamente"
                    helper_text_mode: "on_focus"
                    write_tab: False

                MDTextField:
                    id: descricao
                    hint_text: "Descrição"
                    pos_hint: {"center_x": 0.5}
                    size_hint_x: .8
                    password: False
                    icon_right: 'message'
                    icon_right_color: app.theme_cls.primary_color
                    required: True
                    helper_text_mode: "on_error"
                    helper_text: "Você precisa informar o nome do produto"
                    write_tab: False

                MDTextField:
                    id: venda
                    hint_text: "Valor de venda"
                    pos_hint: {"center_x": 0.5}
                    input_filter: 'float'
                    size_hint_x: .8
                    password: False
                    icon_right: 'currency-brl'
                    icon_right_color: app.theme_cls.primary_color
                    required: True
                    helper_text_mode: "on_error"
                    helper_text: "Você precisa informar o valor do produto"
                    write_tab: False

                MDTextField:
                    id: custo
                    hint_text: "Valor de custo (opcional)"
                    pos_hint: {"center_x": 0.5}
                    size_hint_x: .8
                    input_filter: 'float'
                    password: False
                    icon_right: 'currency-brl'
                    icon_right_color: app.theme_cls.primary_color
                    required: False
                    helper_text_mode: "on_focus"
                    helper_text: "Informe quanto custou do produto"
                    write_tab: False

                MDTextField:
                    id: observacao
                    hint_text: "Observações"
                    pos_hint: {"center_x": 0.5}
                    size_hint_x: .8
                    password: False
                    icon_right: 'comment-text'
                    icon_right_color: app.theme_cls.primary_color
                    helper_text: "Informe alguma observação"
                    helper_text_mode: "on_focus"
                    write_tab: False

                MDFillRoundFlatButton:
                    text: 'Cadastrar'
                    md_bg_color: app.theme_cls.primary_color
                    pos_hint: {"center_x": 0.5, "center_y": 0.35}
                    size_hint_x: .4
                    text_color: 1,1,1,1
                    on_press: root.produto(codigo.text, barcode.text, descricao.text, venda.text, custo.text, observacao.text)
